# Generated by Django 5.0 on 2025-12-20 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRSDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=500)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='crs/pdfs/')),
                ('google_sheet_id', models.CharField(blank=True, max_length=200, null=True)),
                ('google_sheet_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_review', 'In Review'), ('processing', 'Processing'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('total_comments', models.IntegerField(default=0)),
                ('resolved_comments', models.IntegerField(default=0)),
                ('pending_comments', models.IntegerField(default=0)),
                ('project_name', models.CharField(blank=True, max_length=300, null=True)),
                ('contractor_name', models.CharField(blank=True, max_length=300, null=True)),
                ('revision_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crs_documents_assigned', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crs_documents_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRS Document',
                'verbose_name_plural': 'CRS Documents',
                'db_table': 'crs_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRSComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField()),
                ('page_number', models.IntegerField()),
                ('clause_number', models.CharField(blank=True, max_length=100, null=True)),
                ('comment_text', models.TextField()),
                ('comment_type', models.CharField(choices=[('red_comment', 'Red Comment'), ('yellow_box', 'Yellow Box'), ('annotation', 'Annotation'), ('shape', 'Shape'), ('other', 'Other')], default='other', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('color_rgb', models.JSONField(blank=True, help_text='RGB color values', null=True)),
                ('bbox', models.JSONField(blank=True, help_text='Bounding box coordinates', null=True)),
                ('contractor_response', models.TextField(blank=True, null=True)),
                ('contractor_response_date', models.DateTimeField(blank=True, null=True)),
                ('company_response', models.TextField(blank=True, null=True)),
                ('company_response_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_crs_comments', to=settings.AUTH_USER_MODEL)),
                ('company_responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company_responses', to=settings.AUTH_USER_MODEL)),
                ('contractor_responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contractor_responses', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crs.crsdocument')),
            ],
            options={
                'verbose_name': 'CRS Comment',
                'verbose_name_plural': 'CRS Comments',
                'db_table': 'crs_comments',
                'ordering': ['document', 'serial_number'],
                'unique_together': {('document', 'serial_number')},
            },
        ),
        migrations.CreateModel(
            name='CRSActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('status_changed', 'Status Changed'), ('comment_added', 'Comment Added'), ('response_added', 'Response Added'), ('assigned', 'Assigned'), ('exported', 'Exported to Google Sheets'), ('imported', 'Imported from PDF')], max_length=30)),
                ('description', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crs.crscomment')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crs.crsdocument')),
            ],
            options={
                'verbose_name': 'CRS Activity',
                'verbose_name_plural': 'CRS Activities',
                'db_table': 'crs_activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='GoogleSheetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client_id', models.CharField(blank=True, max_length=500, null=True)),
                ('client_secret', models.CharField(blank=True, max_length=500, null=True)),
                ('credentials_json', models.TextField(blank=True, help_text='Full credentials JSON', null=True)),
                ('token_json', models.TextField(blank=True, help_text='OAuth token JSON', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Google Sheet Configuration',
                'verbose_name_plural': 'Google Sheet Configurations',
                'db_table': 'crs_google_sheet_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
