# Generated by Django 5.0 on 2026-01-02 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CRSRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_number', models.IntegerField()),
                ('revision_label', models.CharField(help_text='e.g., Rev 1, Rev 2, Rev 2A', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('comments_received', 'Comments Received'), ('responses_pending', 'Responses Pending'), ('completed', 'Completed'), ('superseded', 'Superseded')], default='draft', max_length=30)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('total_new_comments', models.IntegerField(default=0, help_text='New comments in this revision')),
                ('total_carryover_comments', models.IntegerField(default=0, help_text='Comments from previous revisions')),
                ('total_resolved_comments', models.IntegerField(default=0)),
                ('ai_complexity_score', models.FloatField(default=0.0, help_text='AI-calculated complexity (0-100)')),
                ('ai_estimated_resolution_time_hours', models.FloatField(default=0.0)),
                ('ai_critical_issues_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='revision_info', to='crs.crsdocument')),
                ('parent_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_revisions', to='crs.crsrevision')),
            ],
            options={
                'verbose_name': 'CRS Revision',
                'verbose_name_plural': 'CRS Revisions',
                'db_table': 'crs_revisions',
                'ordering': ['chain', 'revision_number'],
            },
        ),
        migrations.CreateModel(
            name='CRSRevisionChain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chain_id', models.CharField(help_text='Unique identifier for this revision chain', max_length=100, unique=True)),
                ('project_name', models.CharField(max_length=300)),
                ('document_number', models.CharField(max_length=100)),
                ('document_title', models.CharField(max_length=500)),
                ('contractor_name', models.CharField(blank=True, max_length=300, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_hold', 'On Hold'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='active', max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical - Near Rejection')], default='low', max_length=20)),
                ('total_revisions', models.IntegerField(default=0)),
                ('current_revision_number', models.IntegerField(default=1)),
                ('max_allowed_revisions', models.IntegerField(default=5, help_text='Maximum revisions before rejection')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_risk_score', models.FloatField(default=0.0, help_text='AI-calculated risk score (0-100)')),
                ('ai_recommendation', models.TextField(blank=True, help_text='AI-generated recommendation', null=True)),
                ('ai_predicted_completion_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_revision_chains', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CRS Revision Chain',
                'verbose_name_plural': 'CRS Revision Chains',
                'db_table': 'crs_revision_chains',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRSRevisionActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('chain_created', 'Chain Created'), ('revision_added', 'Revision Added'), ('comments_imported', 'Comments Imported'), ('comment_linked', 'Comment Linked'), ('ai_insight_generated', 'AI Insight Generated'), ('risk_level_changed', 'Risk Level Changed'), ('status_changed', 'Status Changed'), ('revision_superseded', 'Revision Superseded')], max_length=30)),
                ('description', models.TextField()),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crs.crsrevision')),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crs.crsrevisionchain')),
            ],
            options={
                'verbose_name': 'CRS Revision Activity',
                'verbose_name_plural': 'CRS Revision Activities',
                'db_table': 'crs_revision_activities',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.AddField(
            model_name='crsrevision',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='crs.crsrevisionchain'),
        ),
        migrations.CreateModel(
            name='CRSAIInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('risk_assessment', 'Risk Assessment'), ('response_suggestion', 'Response Suggestion'), ('pattern_detection', 'Pattern Detection'), ('resolution_prediction', 'Resolution Prediction'), ('priority_recommendation', 'Priority Recommendation'), ('escalation_alert', 'Escalation Alert')], max_length=30)),
                ('severity', models.CharField(choices=[('info', 'Information'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence (0-100)')),
                ('ai_model_used', models.CharField(default='gpt-4', help_text='AI model used for this insight', max_length=100)),
                ('recommended_action', models.TextField(blank=True, null=True)),
                ('suggested_response', models.TextField(blank=True, help_text='AI-suggested response text', null=True)),
                ('was_helpful', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='crs.crscomment')),
                ('dismissed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dismissed_insights', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='crs.crsrevision')),
                ('chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_insights', to='crs.crsrevisionchain')),
            ],
            options={
                'verbose_name': 'CRS AI Insight',
                'verbose_name_plural': 'CRS AI Insights',
                'db_table': 'crs_ai_insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRSCommentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('identical', 'Identical Comment'), ('modified', 'Modified Comment'), ('related', 'Related Comment'), ('resolved_reopened', 'Resolved but Reopened')], max_length=30)),
                ('similarity_score', models.FloatField(default=0.0, help_text='AI-calculated similarity (0-100)')),
                ('ai_detected', models.BooleanField(default=False, help_text='Was this link detected by AI?')),
                ('ai_confidence', models.FloatField(default=0.0, help_text='AI confidence level (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('source_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_source', to='crs.crscomment')),
                ('target_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_as_target', to='crs.crscomment')),
                ('source_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_links_from', to='crs.crsrevision')),
                ('target_revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_links_to', to='crs.crsrevision')),
            ],
            options={
                'verbose_name': 'CRS Comment Link',
                'verbose_name_plural': 'CRS Comment Links',
                'db_table': 'crs_comment_links',
                'ordering': ['source_revision', 'target_revision'],
                'indexes': [models.Index(fields=['source_revision', 'target_revision'], name='crs_comment_source__6841ff_idx')],
                'unique_together': {('source_comment', 'target_comment')},
            },
        ),
        migrations.AddIndex(
            model_name='crsrevisionchain',
            index=models.Index(fields=['chain_id'], name='crs_revisio_chain_i_016ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='crsrevisionchain',
            index=models.Index(fields=['project_name', 'document_number'], name='crs_revisio_project_189839_idx'),
        ),
        migrations.AddIndex(
            model_name='crsrevision',
            index=models.Index(fields=['chain', 'revision_number'], name='crs_revisio_chain_i_6e7ad0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crsrevision',
            unique_together={('chain', 'revision_number')},
        ),
        migrations.AddIndex(
            model_name='crsaiinsight',
            index=models.Index(fields=['chain', 'insight_type'], name='crs_ai_insi_chain_i_fc234d_idx'),
        ),
        migrations.AddIndex(
            model_name='crsaiinsight',
            index=models.Index(fields=['severity', 'is_active'], name='crs_ai_insi_severit_21af8b_idx'),
        ),
    ]
