"""
Migration — adds PumpHydraulicSnapshot for the cloud-backed history feature.
Hand-written (not autogenerated) to avoid touching unrelated drift on
PumpCalculationData fields.
"""
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('process_datasheet', '0017_add_datasheet_template_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PumpHydraulicSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_key', models.CharField(db_index=True, max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('source', models.CharField(
                    choices=[
                        ('ai_extraction', 'AI Extracted'),
                        ('manual', 'Manual Save'),
                        ('auto', 'Auto Save'),
                    ],
                    db_index=True, default='manual', max_length=32,
                )),
                ('project_title',  models.CharField(blank=True, default='', max_length=255)),
                ('job_no',         models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('client_name',    models.CharField(blank=True, default='', max_length=255)),
                ('pump_tag_no',    models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('calculation_no', models.CharField(blank=True, default='', max_length=255)),
                ('form_state', models.JSONField(default=dict, help_text='Full client form state')),
                ('context',    models.JSONField(blank=True, default=dict, help_text='Snapshot context (e.g. extraction summary)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    db_index=True,
                    on_delete=models.deletion.CASCADE,
                    related_name='pump_hydraulic_snapshots',
                    to=settings.AUTH_USER_MODEL,
                )),
            ],
            options={
                'verbose_name': 'Pump Hydraulic Snapshot',
                'verbose_name_plural': 'Pump Hydraulic Snapshots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pumphydraulicsnapshot',
            index=models.Index(fields=['user', 'project_key', '-created_at'],
                               name='ph_snap_user_proj_idx'),
        ),
        migrations.AddIndex(
            model_name='pumphydraulicsnapshot',
            index=models.Index(fields=['user', '-created_at'],
                               name='ph_snap_user_idx'),
        ),
    ]
