# Generated by Django 5.0 on 2026-04-03 09:47

import apps.sld_verification.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SLDDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=512)),
                ('s3_path', models.CharField(blank=True, max_length=1024)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 of the raw file – enables deterministic caching', max_length=64)),
                ('original_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.sld_verification.models._sld_upload_path)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('excel_s3_url', models.CharField(blank=True, max_length=1024)),
                ('pdf_s3_url', models.CharField(blank=True, max_length=1024)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sld_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sld_documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SLDDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_id', models.CharField(blank=True, help_text='Sheet / drawing number', max_length=128)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('page_index', models.IntegerField(default=0, help_text='0-based page index in the PDF')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='sld_verification.slddocument')),
            ],
            options={
                'db_table': 'sld_drawings',
                'ordering': ['page_index'],
            },
        ),
        migrations.CreateModel(
            name='SLDFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.IntegerField(default=0)),
                ('category', models.CharField(max_length=64)),
                ('issue_observed', models.TextField()),
                ('action_required', models.TextField(blank=True)),
                ('evidence', models.TextField(blank=True)),
                ('direction', models.CharField(blank=True, max_length=64)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Info')], default='minor', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='open', max_length=20)),
                ('rule_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='sld_verification.slddrawing')),
            ],
            options={
                'db_table': 'sld_findings',
                'ordering': ['sl_no'],
            },
        ),
        migrations.CreateModel(
            name='SLDProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sld_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sld_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='slddocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sld_verification.sldproject'),
        ),
        migrations.AddIndex(
            model_name='sldproject',
            index=models.Index(fields=['project_id'], name='sld_project_project_613353_idx'),
        ),
        migrations.AddIndex(
            model_name='slddocument',
            index=models.Index(fields=['document_id'], name='sld_documen_documen_2986d6_idx'),
        ),
        migrations.AddIndex(
            model_name='slddocument',
            index=models.Index(fields=['file_hash'], name='sld_documen_file_ha_7c1d4c_idx'),
        ),
    ]
