# Generated by Django 4.2.16 on 2025-12-13 05:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PIDAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_issues', models.IntegerField(default=0)),
                ('approved_count', models.IntegerField(default=0)),
                ('ignored_count', models.IntegerField(default=0)),
                ('pending_count', models.IntegerField(default=0)),
                ('report_data', models.JSONField(help_text='Full analysis report in JSON format')),
                ('pdf_report', models.FileField(blank=True, help_text='Generated PDF report', null=True, upload_to='pid_reports/%Y/%m/%d/')),
                ('excel_report', models.FileField(blank=True, help_text='Generated Excel report', null=True, upload_to='pid_reports/%Y/%m/%d/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'P&ID Analysis Report',
                'verbose_name_plural': 'P&ID Analysis Reports',
            },
        ),
        migrations.CreateModel(
            name='PIDIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(help_text='Sequential issue number')),
                ('pid_reference', models.CharField(help_text='P&ID element reference (tag, line number, etc.)', max_length=200)),
                ('issue_observed', models.TextField(help_text='Detailed description of the issue')),
                ('action_required', models.TextField(help_text='Recommended corrective action')),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('observation', 'Observation')], default='observation', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Equipment, Instrumentation, Piping, etc.', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('ignored', 'Ignored')], default='pending', max_length=20)),
                ('approval', models.CharField(default='Pending', max_length=50)),
                ('remark', models.TextField(blank=True, default='Pending')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='pid_analysis.pidanalysisreport')),
            ],
            options={
                'verbose_name': 'P&ID Issue',
                'verbose_name_plural': 'P&ID Issues',
                'ordering': ['serial_number'],
            },
        ),
        migrations.CreateModel(
            name='PIDDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='P&ID drawing in PDF format', upload_to='pid_drawings/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('drawing_number', models.CharField(blank=True, help_text='P&ID number (e.g., 16-01-08-1678-1)', max_length=100)),
                ('drawing_title', models.CharField(blank=True, max_length=255)),
                ('revision', models.CharField(blank=True, max_length=20)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('analysis_started_at', models.DateTimeField(blank=True, null=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_drawings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P&ID Drawing',
                'verbose_name_plural': 'P&ID Drawings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pidanalysisreport',
            name='pid_drawing',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_report', to='pid_analysis.piddrawing'),
        ),
    ]
