# Generated by Django 4.2.16 on 2025-12-15 05:46

import apps.pid_analysis.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piddrawing',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if analysis failed', null=True),
        ),
        migrations.AlterField(
            model_name='piddrawing',
            name='file',
            field=models.FileField(help_text='P&ID drawing in PDF format (stored in S3 if USE_S3=True)', upload_to=apps.pid_analysis.models.pid_drawing_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
