# Generated by Django 4.2.16 on 2025-12-15 08:33

import apps.pid_analysis.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pid_analysis', '0002_piddrawing_error_message_alter_piddrawing_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Document title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Document description')),
                ('category', models.CharField(choices=[('standard', 'Industry Standard'), ('guideline', 'Design Guideline'), ('specification', 'Technical Specification'), ('best_practice', 'Best Practice'), ('company_standard', 'Company Standard'), ('regulation', 'Regulation/Code'), ('other', 'Other')], default='other', max_length=50)),
                ('file', models.FileField(help_text='Reference document file', upload_to=apps.pid_analysis.models.reference_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'docx', 'doc'])])),
                ('original_filename', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('content_text', models.TextField(blank=True, help_text='Extracted text content for RAG')),
                ('chunk_count', models.IntegerField(default=0, help_text='Number of chunks created for RAG')),
                ('vector_db_ids', models.JSONField(blank=True, default=list, help_text='Vector database document IDs')),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('version', models.CharField(blank=True, max_length=50)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Searchable tags')),
                ('is_active', models.BooleanField(default=True, help_text='Include in RAG context retrieval')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reference Document',
                'verbose_name_plural': 'Reference Documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='pid_analysi_categor_26902c_idx'), models.Index(fields=['embedding_status'], name='pid_analysi_embeddi_87144f_idx')],
            },
        ),
    ]
