# Generated by Django 5.0 on 2025-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0003_referencedocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='pidissue',
            name='location_on_drawing',
            field=models.JSONField(blank=True, help_text='Location information: zone, drawing_section, proximity_description, visual_cues', null=True),
        ),
    ]
