# Generated by Django 4.2.16 on 2025-12-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid_analysis', '0004_pidissue_location_on_drawing'),
    ]

    operations = [
        migrations.AddField(
            model_name='piddrawing',
            name='area',
            field=models.CharField(blank=True, help_text='Area code (2 digits)', max_length=2),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='doc_code',
            field=models.CharField(blank=True, help_text='Document code (2 digits)', max_length=2),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='p_area',
            field=models.CharField(blank=True, help_text='P/Area code (2 digits)', max_length=2),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='rev',
            field=models.CharField(blank=True, help_text='Revision (1 digit)', max_length=1),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number (4 digits)', max_length=4),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='sheet_number',
            field=models.CharField(blank=True, default='1', help_text='Sheet number', max_length=1),
        ),
        migrations.AddField(
            model_name='piddrawing',
            name='total_sheets',
            field=models.CharField(blank=True, default='1', help_text='Total sheets', max_length=1),
        ),
    ]
