# Generated by Django 4.2.16 on 2026-02-10 05:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def check_and_create_pidproject_table(apps, schema_editor):
    """
    SOFT-CODED IDEMPOTENT TABLE CREATION
    Only create PIDProject table and related objects if they don't exist
    """
    from django.db import connection
    
    table_name = 'pid_projects'
    
    with connection.cursor() as cursor:
        # Check if table exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = %s
            )
        """, [table_name])
        
        table_exists = cursor.fetchone()[0]
        
        if not table_exists:
            print(f"✅ Creating table '{table_name}'...")
            # Create the PIDProject table
            cursor.execute("""
                CREATE TABLE pid_projects (
                    id BIGSERIAL PRIMARY KEY,
                    project_id VARCHAR(50) UNIQUE NOT NULL,
                    project_name VARCHAR(255) NOT NULL,
                    description TEXT NULL,
                    organization VARCHAR(255),
                    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    created_by_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE
                )
            """)
            
            # Create indexes
            cursor.execute("""
                CREATE INDEX pid_project_project_209c56_idx ON pid_projects (project_id)
            """)
            cursor.execute("""
                CREATE INDEX pid_project_created_09046f_idx ON pid_projects (created_by_id, created_at DESC)
            """)
            cursor.execute("""
                CREATE INDEX pid_project_organiz_a8e179_idx ON pid_projects (organization)
            """)
            
            print(f"✅ Created table '{table_name}' with indexes")
        else:
            print(f"ℹ️  Table '{table_name}' already exists - skipping")
        
        # Check and add project ForeignKey to pid_analysis_piddrawing
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'pid_analysis_piddrawing' 
                AND column_name = 'project_id'
            )
        """)
        
        column_exists = cursor.fetchone()[0]
        
        if not column_exists:
            print("✅ Adding 'project_id' column to pid_analysis_piddrawing...")
            cursor.execute("""
                ALTER TABLE pid_analysis_piddrawing 
                ADD COLUMN project_id BIGINT NULL 
                REFERENCES pid_projects(id) ON DELETE CASCADE
            """)
            print("✅ Added 'project_id' foreign key column")
        else:
            print("ℹ️  Column 'project_id' already exists in pid_analysis_piddrawing - skipping")


def reverse_pidproject_table(apps, schema_editor):
    """Remove PIDProject table and related objects if migration is reversed"""
    from django.db import connection
    
    with connection.cursor() as cursor:
        # Drop foreign key column first
        cursor.execute("""
            ALTER TABLE pid_analysis_piddrawing 
            DROP COLUMN IF EXISTS project_id CASCADE
        """)
        
        # Drop the table (CASCADE will drop indexes)
        cursor.execute("DROP TABLE IF EXISTS pid_projects CASCADE")


class Migration(migrations.Migration):
    # Mark as non-initial to enable smart checking
    initial = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('pid_analysis', '0005_piddrawing_area_piddrawing_doc_code_and_more'),
    ]

    operations = [
        # Use RunPython for idempotent table creation
        migrations.RunPython(
            check_and_create_pidproject_table,
            reverse_pidproject_table
        ),
    ]
