# Generated by Django 4.2.16 on 2025-12-15 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFDDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_title', models.CharField(blank=True, max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('revision', models.CharField(blank=True, max_length=50)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('project_code', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(upload_to='pfd_documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('file_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('converted', 'Converted'), ('failed', 'Failed'), ('approved', 'Approved')], default='uploaded', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_duration', models.FloatField(blank=True, help_text='Duration in seconds', null=True)),
                ('extracted_data', models.JSONField(default=dict, help_text='Extracted process information from PFD')),
                ('conversion_notes', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfd_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PFD Document',
                'verbose_name_plural': 'PFD Documents',
                'db_table': 'pfd_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PIDConversion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pid_drawing_number', models.CharField(max_length=100)),
                ('pid_title', models.CharField(max_length=255)),
                ('pid_revision', models.CharField(default='A', max_length=50)),
                ('pid_file', models.FileField(blank=True, null=True, upload_to='pid_generated/%Y/%m/%d/')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='pid_previews/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed'), ('approved', 'Approved')], default='generating', max_length=20)),
                ('generation_started_at', models.DateTimeField(auto_now_add=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation_duration', models.FloatField(blank=True, null=True)),
                ('equipment_list', models.JSONField(default=list, help_text='List of equipment from PFD')),
                ('instrument_list', models.JSONField(default=list, help_text='Generated instrumentation')),
                ('piping_details', models.JSONField(default=list, help_text='Piping specifications')),
                ('safety_systems', models.JSONField(default=list, help_text='Safety and control systems')),
                ('design_parameters', models.JSONField(default=dict, help_text='Process parameters, pressures, temperatures, etc.')),
                ('compliance_checks', models.JSONField(default=dict, help_text='Standards compliance verification')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0-100)', null=True)),
                ('converted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_conversions', to=settings.AUTH_USER_MODEL)),
                ('pfd_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_conversions', to='pfd_converter.pfddocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_conversions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'P&ID Conversion',
                'verbose_name_plural': 'P&ID Conversions',
                'db_table': 'pid_conversions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversionFeedback',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('accuracy_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('completeness_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('usability_rating', models.IntegerField(blank=True, choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], null=True)),
                ('comments', models.TextField(blank=True)),
                ('suggested_improvements', models.TextField(blank=True)),
                ('issues_found', models.JSONField(default=list, help_text='List of issues or errors found')),
                ('conversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pfd_converter.pidconversion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversion Feedback',
                'verbose_name_plural': 'Conversion Feedback',
                'db_table': 'pfd_conversion_feedback',
                'ordering': ['-created_at'],
                'unique_together': {('conversion', 'user')},
            },
        ),
    ]
