# Generated by Django 5.0 on 2025-12-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfd_converter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pfddocument',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to='pfd_documents/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='pidconversion',
            name='assumptions_report',
            field=models.TextField(blank=True, help_text='Assumptions and limitations report'),
        ),
        migrations.AddField(
            model_name='pidconversion',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Conversion completion timestamp', null=True),
        ),
        migrations.AddField(
            model_name='pidconversion',
            name='conversion_data',
            field=models.JSONField(blank=True, help_text='Complete conversion data from 6-step workflow', null=True),
        ),
        migrations.AddField(
            model_name='pidconversion',
            name='conversion_method',
            field=models.CharField(default='standard', help_text='Conversion method: standard/ai_assisted_6step', max_length=50),
        ),
        migrations.AddField(
            model_name='pidconversion',
            name='pid_pdf',
            field=models.BinaryField(blank=True, help_text='Generated P&ID PDF bytes', null=True),
        ),
        migrations.AddField(
            model_name='pidconversion',
            name='valve_list',
            field=models.TextField(blank=True, help_text='JSON string of valve list'),
        ),
        migrations.AlterField(
            model_name='pfddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='pfd_documents/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='pfddocument',
            name='file_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='pfddocument',
            name='file_size',
            field=models.BigIntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='pfddocument',
            name='file_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='pfddocument',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('converted', 'Converted'), ('failed', 'Failed'), ('approved', 'Approved')], default='uploaded', max_length=20),
        ),
    ]
