# Generated by Django 5.0 on 2026-04-01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CrossRecommendationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('source_type', models.CharField(choices=[('pid', 'P&ID'), ('pfd', 'PFD')], max_length=10)),
                ('source_document_id', models.UUIDField(db_index=True)),
                ('target_type', models.CharField(choices=[('pid', 'P&ID'), ('pfd', 'PFD')], max_length=10)),
                ('target_document_id', models.UUIDField(db_index=True)),
                ('project_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('score', models.FloatField(default=0.0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(choices=[('suggested', 'Suggested'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('auto', 'Auto Matched')], default='suggested', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cross_recommendation_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cross_recommendation_links',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crossrecommendationlink',
            index=models.Index(fields=['source_type', 'source_document_id'], name='cross_recom_source__e59eca_idx'),
        ),
        migrations.AddIndex(
            model_name='crossrecommendationlink',
            index=models.Index(fields=['target_type', 'target_document_id'], name='cross_recom_target__7d77b4_idx'),
        ),
        migrations.AddIndex(
            model_name='crossrecommendationlink',
            index=models.Index(fields=['project_id', '-updated_at'], name='cross_recom_project_6d8f4f_idx'),
        ),
        migrations.AddIndex(
            model_name='crossrecommendationlink',
            index=models.Index(fields=['decision'], name='cross_recom_decisio_2e9d00_idx'),
        ),
        migrations.AddConstraint(
            model_name='crossrecommendationlink',
            constraint=models.UniqueConstraint(fields=('source_type', 'source_document_id', 'target_type', 'target_document_id'), name='uq_cross_recommendation_link_pair'),
        ),
    ]
