# Generated by Django 5.0 on 2026-04-09 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wrench_integration', '0003_wrenchconfig_is_password_encrypted_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WrenchS3SyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('batch', 'Batch – full export, run once'), ('realtime', 'Real-time – continuous polling')], default='batch', max_length=20)),
                ('entity_type', models.CharField(choices=[('transmittals', 'Transmittals'), ('documents', 'Documents'), ('all', 'All (Transmittals + Documents)')], default='transmittals', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('s3_prefix', models.CharField(blank=True, default='wrench/', help_text='S3 key prefix, e.g. "wrench/transmittals/"', max_length=500)),
                ('records_exported', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('pages_processed', models.IntegerField(default=0)),
                ('last_page_exported', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('job_details', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('config', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='s3_sync_jobs', to='wrench_integration.wrenchconfig')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wrench_s3_sync_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wrench S3 Sync Job',
                'verbose_name_plural': 'Wrench S3 Sync Jobs',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status'], name='wrench_inte_status_6a4a95_idx'), models.Index(fields=['mode'], name='wrench_inte_mode_c7f789_idx'), models.Index(fields=['started_at'], name='wrench_inte_started_a61cab_idx')],
            },
        ),
    ]
