# Generated by Django 5.0 on 2025-12-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_first_login',
            field=models.BooleanField(default=True, help_text='True if user has not logged in yet'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='Last time password was changed', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='must_reset_password',
            field=models.BooleanField(default=False, help_text='True if user must reset password'),
        ),
        migrations.AddField(
            model_name='user',
            name='temp_password_created_at',
            field=models.DateTimeField(blank=True, help_text='When temporary password was set', null=True),
        ),
    ]
