"""
Export Service
==============
Generates Excel and PDF quality reports from stored findings.
Uploads results to AWS S3 and returns public/presigned URLs.
"""
import io
import logging
import os
import re as _re
import tempfile
from typing import Optional

logger = logging.getLogger(__name__)

# Soft-coded: categories excluded from all exports (Excel + PDF).
# Connectivity findings are omitted — orphan-node graph checks produce too many
# false-positives on scanned drawings and are not useful to process engineers.
HIDDEN_CATEGORIES = {'connectivity'}

# Column order for the findings report
FINDINGS_COLUMNS = [
    'SL No', 'Drawing ID', 'Category', 'Rule ID',
    'Issue Observed', 'Action Required', 'Evidence',
    'Direction', 'Severity', 'Status',
]

# ── Soft-coded report configuration ──────────────────────────────────────────
# All company details, colours, and behaviour flags are defined here.
# Rebrand by editing this dict — no rendering logic needs to change.
REPORT_CONFIG = {
    'company': {
        'name':        'Rejlers',
        'tagline':     'Engineering & Consulting',
        'website':     'www.rejlers.se',
        'email':       'info@rejlers.se',
        'prepared_by': 'Process & Instrumentation Team',
    },
    'branding': {
        'primary':   '#003F6E',   # Rejlers navy blue
        'accent':    '#E8501A',   # Rejlers accent orange
        'light_bg':  '#F4F7FB',
        'alt_row':   '#EAF0F8',
        'white':     '#FFFFFF',
        'text_dark': '#1A1A2E',
        'text_mid':  '#6B7280',
        'divider':   '#CBD5E1',
    },
    'report': {
        'title':           'P&ID Quality Verification Report',
        'subtitle':        'AI-Assisted Drawing Review',
        'tool_name':       'AIFlow P&ID Verifier',
        'confidentiality': 'CONFIDENTIAL \u2014 For Client Internal Use Only',
        'system_label':    'Generated by AIFlow Intelligence Platform',
    },
    # Severity display helpers (hex codes, no leading #)
    'severity': {
        'CRITICAL': {'hex': 'DC2626', 'bg_hex': 'FEE2E2'},
        'MAJOR':    {'hex': 'EA580C', 'bg_hex': 'FFEDD5'},
        'MINOR':    {'hex': 'B45309', 'bg_hex': 'FEF9C3'},
        'INFO':     {'hex': '1D4ED8', 'bg_hex': 'DBEAFE'},
    },
    # Drawing overlay: render the PDF page and paint finding markers on it
    'drawing_overlay': {
        'enabled':       True,
        'dpi':           150,     # render DPI (balance quality vs file size)
        'marker_radius': 14,      # pixels at render DPI
        # RGBA tuples for each severity level
        'severity_rgba': {
            'critical': (220, 38,  38,  230),
            'major':    (234, 88,  12,  230),
            'minor':    (202, 138, 4,   230),
            'info':     (37,  99,  235, 210),
        },
    },
}


# ---------------------------------------------------------------------------
# Excel
# ---------------------------------------------------------------------------

def generate_excel(document) -> Optional[bytes]:
    """
    Build an Excel workbook from all findings for `document`.
    Returns raw bytes or None on failure.
    Uses pandas + openpyxl (deterministic output: same data → same file).
    """
    try:
        import pandas as pd
        from openpyxl.styles import PatternFill, Font, Alignment, Border, Side
        from openpyxl.utils import get_column_letter
    except ImportError:
        logger.error('[Export] pandas/openpyxl not installed')
        return None

    rows = []
    for drawing in document.drawings.order_by('page_index'):
        for finding in drawing.findings.order_by('sl_no'):
            if finding.category in HIDDEN_CATEGORIES:
                continue
            rows.append({
                'SL No':           finding.sl_no,
                'Drawing ID':      drawing.drawing_id,
                'Category':        finding.get_category_display(),
                'Rule ID':         finding.rule_id,
                'Issue Observed':  finding.issue_observed,
                'Action Required': finding.action_required,
                'Evidence':        finding.evidence,
                'Direction':       finding.direction,
                'Severity':        finding.severity.upper(),
                'Status':          finding.status.capitalize(),
            })

    df = pd.DataFrame(rows, columns=FINDINGS_COLUMNS) if rows else pd.DataFrame(columns=FINDINGS_COLUMNS)

    buf = io.BytesIO()
    with pd.ExcelWriter(buf, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='P&ID QC Findings')
        wb = writer.book
        ws = writer.sheets['P&ID QC Findings']

        # Header styling
        header_fill   = PatternFill(fill_type='solid', fgColor='2F5496')
        header_font   = Font(bold=True, color='FFFFFF', size=11)
        header_align  = Alignment(horizontal='center', vertical='center', wrap_text=True)

        thin = Side(style='thin', color='000000')
        border = Border(left=thin, right=thin, top=thin, bottom=thin)

        for col_idx, col_name in enumerate(FINDINGS_COLUMNS, start=1):
            cell = ws.cell(row=1, column=col_idx)
            cell.fill   = header_fill
            cell.font   = header_font
            cell.alignment = header_align
            cell.border = border

        # Severity colour coding
        severity_colours = {
            'CRITICAL': 'FF0000',
            'MAJOR':    'FF9900',
            'MINOR':    'FFFF00',
            'INFO':     'D9EAD3',
        }
        severity_col = FINDINGS_COLUMNS.index('Severity') + 1

        for row_idx, row_data in enumerate(rows, start=2):
            sev  = row_data['Severity'].upper()
            colour = severity_colours.get(sev, 'FFFFFF')
            fill = PatternFill(fill_type='solid', fgColor=colour)
            ws.cell(row=row_idx, column=severity_col).fill = fill
            for col_idx in range(1, len(FINDINGS_COLUMNS) + 1):
                ws.cell(row=row_idx, column=col_idx).border = border
                ws.cell(row=row_idx, column=col_idx).alignment = Alignment(wrap_text=True, vertical='top')

        # Auto-fit column widths (max 60 chars)
        for col_idx, col_name in enumerate(FINDINGS_COLUMNS, start=1):
            max_len = max(
                len(col_name),
                *[len(str(r.get(col_name, '') or '')) for r in rows] if rows else [0]
            )
            ws.column_dimensions[get_column_letter(col_idx)].width = min(max_len + 4, 60)

        ws.freeze_panes = 'A2'

    return buf.getvalue()


# ---------------------------------------------------------------------------
# PDF  (using reportlab + optional PyMuPDF / Pillow for drawing overlay)
# ---------------------------------------------------------------------------

def generate_pdf(document) -> Optional[bytes]:
    """
    Professional Rejlers P&ID findings report.

    Structure (simple and clean)
    ----------------------------
    Page 1 : Rejlers header + document metadata + severity stats
    Per drawing : Annotated drawing image (severity-coded numbered markers)
                  followed by the matching findings table.
    Footer bar on every page (company, classification, page number).

    All company details / colours are soft-coded via REPORT_CONFIG.
    Drawing overlay degrades gracefully when PyMuPDF / Pillow are absent.
    """
    import datetime

    RC = REPORT_CONFIG

    try:
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import cm
        from reportlab.platypus import (
            SimpleDocTemplate, Table, TableStyle, Paragraph,
            Spacer, HRFlowable, PageBreak, Image as RLImage,
        )
    except ImportError:
        logger.error('[Export] reportlab not installed')
        return None

    # ── Colour helpers ────────────────────────────────────────────────────────
    def _hx(h):
        h = h.lstrip('#')
        return colors.Color(int(h[0:2], 16) / 255.0,
                            int(h[2:4], 16) / 255.0,
                            int(h[4:6], 16) / 255.0)

    B       = RC['branding']
    COL     = {k: _hx(v) for k, v in B.items()}
    SEV_CFG = RC['severity']
    SEV_BG  = {k: _hx(v['bg_hex']) for k, v in SEV_CFG.items()}

    # ── Page geometry ─────────────────────────────────────────────────────────
    PAGE_W, PAGE_H = landscape(A4)
    L_MAR = R_MAR  = 1.5 * cm
    T_MAR = B_MAR  = 1.6 * cm
    FOOTER_H       = 24   # pt
    AVAIL_W        = PAGE_W - L_MAR - R_MAR
    gen_date       = datetime.datetime.utcnow().strftime('%d %B %Y')

    # ── Styles ────────────────────────────────────────────────────────────────
    base = getSampleStyleSheet()

    def _ps(name, **kw):
        return ParagraphStyle(name, parent=base['Normal'], **kw)

    S = {
        'h2':   _ps('h2',   fontSize=12, fontName='Helvetica-Bold',
                             textColor=COL['primary'], spaceAfter=4, leading=15),
        'body': _ps('body', fontSize=8,  textColor=COL['text_dark'], leading=11),
        'sm':   _ps('sm',   fontSize=7,  textColor=COL['text_mid'],  leading=9),
        'lbl':  _ps('lbl',  fontSize=7.5, fontName='Helvetica-Bold',
                             textColor=COL['text_mid'], leading=10),
        'thdr': _ps('thdr', fontSize=8,  fontName='Helvetica-Bold',
                             textColor=colors.white, alignment=1, leading=10),
        'tcell':_ps('tc',   fontSize=7.5, textColor=COL['text_dark'], leading=10),
    }

    # ── Footer chrome (every page) ────────────────────────────────────────────
    def _chrome(canvas, doc_obj):
        canvas.saveState()
        canvas.setFillColor(COL['primary'])
        canvas.rect(0, 0, PAGE_W, FOOTER_H, fill=1, stroke=0)
        canvas.setFillColor(_hx(B['accent']))
        canvas.rect(0, FOOTER_H, PAGE_W, 2, fill=1, stroke=0)
        canvas.setFont('Helvetica-Bold', 7.5)
        canvas.setFillColor(colors.white)
        canvas.drawString(L_MAR, 7,
                          f'{RC["company"]["name"]}  \u00b7  {RC["company"]["tagline"]}')
        canvas.setFont('Helvetica', 7)
        canvas.setFillColor(colors.HexColor('#A8C4DE'))
        canvas.drawCentredString(PAGE_W / 2, 7, RC['report']['confidentiality'])
        canvas.setFont('Helvetica-Bold', 7.5)
        canvas.setFillColor(colors.white)
        canvas.drawRightString(PAGE_W - R_MAR, 7, f'Page {doc_obj.page}')
        canvas.restoreState()

    # ── Pre-aggregate severity counts ─────────────────────────────────────────
    sev_counts = {k: 0 for k in SEV_CFG}
    total_count = 0
    for drw in document.drawings.order_by('page_index'):
        for f in drw.findings.all():
            if f.category in HIDDEN_CATEGORIES:
                continue
            sk = f.severity.upper()
            sev_counts[sk] = sev_counts.get(sk, 0) + 1
            total_count += 1

    # ── Overlay dependencies (load once, fail gracefully) ─────────────────────
    HAS_OVERLAY = False
    file_path   = None
    if RC['drawing_overlay']['enabled']:
        try:
            from ..tasks import _resolve_file_path
            file_path = _resolve_file_path(document)
            import fitz as _fitz                                              # noqa
            from PIL import Image as _PILImg, ImageDraw as _IDraw            # noqa
            from PIL import ImageFont as _IFont                              # noqa
            HAS_OVERLAY = True
        except Exception as _ov_exc:
            logger.debug('[Export] Drawing overlay unavailable: %s', _ov_exc)

    # ── Coordinate resolver (same NPS-aware logic as the frontend) ────────────
    def _resolve_pos(evidence, tag_positions):
        def _norm(k):
            return (k or '').replace('\u201c', '"').replace('\u201d', '"').strip()
        nk = _norm(evidence)
        for key in (nk, evidence):
            if key in tag_positions:
                tp = tag_positions[key]
                return tp.get('x_pct'), tp.get('y_pct')
        for m in _re.finditer(r'\b(\d+(?:\.\d+)?)\s*["\u201c\u201d]', nk):
            nps = m.group(1) + '"'
            for candidate in (nps, _norm(nps)):
                if candidate in tag_positions:
                    tp = tag_positions[candidate]
                    return tp.get('x_pct'), tp.get('y_pct')
        return None, None

    # ── Annotated drawing renderer ────────────────────────────────────────────
    def _annotated_png(page_index, tagged):
        """
        tagged = [(seq_num, finding, x_pct_or_None, y_pct_or_None), ...]
        Returns (PIL_image, {finding.id: seq_num}) or (None, {}).

        Marker radius scales with the image so circles remain clearly
        visible regardless of the source PDF resolution.
        """
        if not HAS_OVERLAY or file_path is None:
            return None, {}
        try:
            import fitz as _fitz
            from PIL import Image as _PILImg, ImageDraw as _IDraw, ImageFont as _IFont

            dpi      = RC['drawing_overlay']['dpi']
            sev_rgba = RC['drawing_overlay']['severity_rgba']

            pdf = _fitz.open(file_path)
            if page_index >= len(pdf):
                pdf.close()
                return None, {}
            pix = pdf[page_index].get_pixmap(
                matrix=_fitz.Matrix(dpi / 72.0, dpi / 72.0), alpha=False)
            img = _PILImg.frombytes('RGB', [pix.width, pix.height], pix.samples)
            pdf.close()

            img_w, img_h = img.size

            # Scale radius to 2.2 % of the largest image dimension.
            # This keeps markers visible at any source resolution once the
            # image is scaled down to fit the A4 page width.
            radius    = max(30, int(max(img_w, img_h) * 0.022))
            font_size = max(16, int(radius * 0.82))
            border_w  = max(3, radius // 6)

            # Font loading: try common bold TTF names, fall back to PIL default
            font = None
            for _fname in ('DejaVuSans-Bold.ttf', 'LiberationSans-Bold.ttf',
                           'FreeSansBold.ttf', 'Arial.ttf', 'Verdana.ttf'):
                try:
                    font = _IFont.truetype(_fname, font_size)
                    break
                except Exception:
                    pass
            if font is None:
                try:
                    font = _IFont.load_default(size=font_size)
                except Exception:
                    font = _IFont.load_default()

            overlay    = _PILImg.new('RGBA', (img_w, img_h), (0, 0, 0, 0))
            drw        = _IDraw.Draw(overlay)
            marker_map = {}

            for (num, finding, x_pct, y_pct) in tagged:
                if x_pct is None or y_pct is None:
                    continue
                px   = int(x_pct / 100.0 * img_w)
                py   = int(y_pct / 100.0 * img_h)
                rgba = sev_rgba.get(finding.severity.lower(), (100, 100, 100, 220))
                fill = (rgba[0], rgba[1], rgba[2], 225)
                halo = (rgba[0], rgba[1], rgba[2], 55)

                # 1. Outer soft halo (improves visibility on any background)
                drw.ellipse(
                    [(px - radius - 10, py - radius - 10),
                     (px + radius + 10, py + radius + 10)],
                    fill=halo,
                )
                # 2. White backing ring (contrast against dark drawing lines)
                drw.ellipse(
                    [(px - radius - 3, py - radius - 3),
                     (px + radius + 3, py + radius + 3)],
                    fill=(255, 255, 255, 215),
                )
                # 3. Severity-coloured filled circle with white border
                drw.ellipse(
                    [(px - radius, py - radius), (px + radius, py + radius)],
                    fill=fill,
                    outline=(255, 255, 255, 255),
                    width=border_w,
                )
                # 4. Centred sequence number
                label = str(num)
                try:
                    bb = drw.textbbox((0, 0), label, font=font)
                    tw, th = bb[2] - bb[0], bb[3] - bb[1]
                    drw.text((px - tw // 2, py - th // 2),
                             label, fill=(255, 255, 255, 255), font=font)
                except Exception:
                    drw.text((px - 6, py - 8), label, fill=(255, 255, 255, 255))

                marker_map[finding.id] = num

            img = _PILImg.alpha_composite(img.convert('RGBA'), overlay).convert('RGB')
            return img, marker_map
        except Exception as _exc:
            logger.warning('[Export] Overlay render failed: %s', _exc)
            return None, {}

    # ── Build document ────────────────────────────────────────────────────────
    buf    = io.BytesIO()
    rl_doc = SimpleDocTemplate(
        buf,
        pagesize=landscape(A4),
        leftMargin=L_MAR,  rightMargin=R_MAR,
        topMargin=T_MAR,   bottomMargin=B_MAR + FOOTER_H,
    )
    story = []

    # ── Page 1: Rejlers header + document info + severity stats ───────────────
    banner = Table(
        [[Paragraph(RC['company']['name'],
                    _ps('bn', fontSize=22, fontName='Helvetica-Bold',
                        textColor=colors.white, alignment=1, leading=26))],
         [Paragraph(RC['company']['tagline'],
                    _ps('bt', fontSize=10, textColor=colors.HexColor('#A8C4DE'),
                        alignment=1, leading=13))]],
        colWidths=[AVAIL_W],
    )
    banner.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (-1, -1), COL['primary']),
        ('ALIGN',         (0, 0), (-1, -1), 'CENTER'),
        ('TOPPADDING',    (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, -1), (-1, -1), 10),
        ('LINEABOVE',     (0, 0),  (-1, 0),  4, _hx(B['accent'])),
        ('LINEBELOW',     (0, -1), (-1, -1), 3, _hx(B['accent'])),
    ]))
    story.append(banner)
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph(RC['report']['title'], S['h2']))
    story.append(Spacer(1, 0.15 * cm))

    hw = AVAIL_W / 2
    meta = Table(
        [
            [Paragraph('Document',       S['lbl']), Paragraph(document.file_name,             S['body']),
             Paragraph('Generated',      S['lbl']), Paragraph(gen_date,                        S['body'])],
            [Paragraph('Drawings',       S['lbl']), Paragraph(str(document.drawings.count()),  S['body']),
             Paragraph('Prepared by',   S['lbl']), Paragraph(RC['company']['prepared_by'],     S['body'])],
            [Paragraph('Total Findings', S['lbl']), Paragraph(str(total_count),                S['body']),
             Paragraph('Contact',       S['lbl']),
             Paragraph(f'{RC["company"]["email"]}  |  {RC["company"]["website"]}', S['body'])],
        ],
        colWidths=[hw * 0.28, hw * 0.72, hw * 0.28, hw * 0.72],
    )
    meta.setStyle(TableStyle([
        ('BACKGROUND',    (0, 0), (0, -1), COL['light_bg']),
        ('BACKGROUND',    (2, 0), (2, -1), COL['light_bg']),
        ('GRID',          (0, 0), (-1, -1), 0.3, COL['divider']),
        ('FONTSIZE',      (0, 0), (-1, -1), 8),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
        ('LEFTPADDING',   (0, 0), (-1, -1), 6),
    ]))
    story.append(meta)
    story.append(Spacer(1, 0.3 * cm))

    # Severity stats bar
    sev_order = ['CRITICAL', 'MAJOR', 'MINOR', 'INFO']
    sev_human = {'CRITICAL': 'Critical', 'MAJOR': 'Major',
                 'MINOR': 'Minor',       'INFO':  'Informational'}
    sev_cells = []
    for sk in sev_order:
        cnt    = sev_counts.get(sk, 0)
        hfg    = SEV_CFG[sk]['hex']
        hmid   = B['text_mid'].lstrip('#')
        sev_cells.append(Paragraph(
            f'<font size=18 color="#{hfg}"><b>{cnt}</b></font><br/>'
            f'<font size=8 color="#{hmid}">{sev_human[sk]}</font>',
            _ps(f'sv{sk}', alignment=1, leading=20),
        ))
    sev_tbl = Table([sev_cells], colWidths=[AVAIL_W / 4] * 4)
    sev_ts  = [
        ('ALIGN',         (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN',        (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING',    (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
        ('BOX',           (0, 0), (-1, -1), 0.5, COL['divider']),
        ('INNERGRID',     (0, 0), (-1, -1), 0.5, COL['divider']),
    ]
    for i, sk in enumerate(sev_order):
        sev_ts.append(('BACKGROUND', (i, 0), (i, 0), SEV_BG.get(sk, COL['light_bg'])))
    sev_tbl.setStyle(TableStyle(sev_ts))
    story.append(sev_tbl)
    story.append(PageBreak())

    # ── Per-drawing sections: annotated image + findings table ────────────────
    for drw in document.drawings.order_by('page_index'):
        findings = [f for f in drw.findings.order_by('sl_no')
                   if f.category not in HIDDEN_CATEGORIES]
        if not findings:
            continue

        tag_positions = (drw.metadata or {}).get('tag_positions', {})

        # Build tagged list: (seq_num, finding, x_pct, y_pct)
        tagged = []
        for i, f in enumerate(findings, start=1):
            xp, yp = _resolve_pos(f.evidence or '', tag_positions)
            tagged.append((i, f, xp, yp))

        # Section heading
        story.append(Paragraph(
            f'Drawing: {drw.drawing_id}  \u2014  Page {drw.page_index + 1}',
            S['h2'],
        ))
        story.append(HRFlowable(width=AVAIL_W, thickness=1.5, color=_hx(B['accent'])))
        story.append(Spacer(1, 0.2 * cm))

        # Annotated drawing image
        pil_img, marker_map = _annotated_png(drw.page_index, tagged)
        if pil_img is not None:
            img_buf = io.BytesIO()
            pil_img.save(img_buf, format='PNG', optimize=True)
            img_buf.seek(0)

            iw, ih   = pil_img.size
            target_w = AVAIL_W
            target_h = target_w * ih / iw
            # Cap height at 52 % of usable page height so the table still fits
            max_h    = (PAGE_H - T_MAR - B_MAR - FOOTER_H) * 0.52
            if target_h > max_h:
                target_h = max_h
                target_w = target_h * iw / ih

            story.append(RLImage(img_buf, width=target_w, height=target_h))
            has_coords = any(xp is not None for _, _, xp, _ in tagged)
            story.append(Paragraph(
                'Numbered circles mark finding locations \u2014 colours match severity (Critical\u00a0=\u00a0red, Major\u00a0=\u00a0orange, Minor\u00a0=\u00a0amber, Info\u00a0=\u00a0blue). '
                'Match each number to the table below.'
                if has_coords else
                'Drawing rendered from source PDF. No coordinate data available for this page.',
                S['sm'],
            ))
            story.append(Spacer(1, 0.2 * cm))
        else:
            story.append(Paragraph('Drawing image not available.', S['sm']))
            story.append(Spacer(1, 0.15 * cm))

        # Findings table
        hdr = [Paragraph(h, S['thdr'])
               for h in ['#', 'Rule', 'Category', 'Issue Observed',
                         'Action Required', 'Severity', 'Status']]
        rows = [hdr]
        sev_bg_cmds = []
        for ri, (num, f, _, _) in enumerate(tagged, start=1):
            sk  = f.severity.upper()
            hfg = SEV_CFG.get(sk, {}).get('hex', B['text_dark'].lstrip('#'))
            rows.append([
                Paragraph(f'<b>{marker_map.get(f.id, num)}</b>', S['tcell']),
                Paragraph(str(f.rule_id or ''),               S['tcell']),
                Paragraph(f.get_category_display(),           S['tcell']),
                Paragraph(str(f.issue_observed  or '')[:280], S['tcell']),
                Paragraph(str(f.action_required or '')[:220], S['tcell']),
                Paragraph(f'<font color="#{hfg}"><b>{sk}</b></font>', S['tcell']),
                Paragraph(f.status.capitalize(),              S['tcell']),
            ])
            if sk in SEV_BG:
                sev_bg_cmds.append(('BACKGROUND', (5, ri), (5, ri), SEV_BG[sk]))

        cw  = [AVAIL_W * p for p in [0.04, 0.07, 0.12, 0.37, 0.28, 0.07, 0.05]]
        tbl = Table(rows, colWidths=cw, repeatRows=1)
        tbl.setStyle(TableStyle([
            ('BACKGROUND',     (0, 0), (-1, 0),  COL['primary']),
            ('FONTSIZE',       (0, 0), (-1, -1), 7.5),
            ('ALIGN',          (0, 0), (1, -1),  'CENTER'),
            ('ALIGN',          (5, 0), (6, -1),  'CENTER'),
            ('GRID',           (0, 0), (-1, -1), 0.25, COL['divider']),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, COL['light_bg']]),
            ('VALIGN',         (0, 0), (-1, -1), 'TOP'),
            ('TOPPADDING',     (0, 0), (-1, -1), 3),
            ('BOTTOMPADDING',  (0, 0), (-1, -1), 3),
            ('LEFTPADDING',    (0, 0), (-1, -1), 4),
        ] + sev_bg_cmds))
        story.append(tbl)
        story.append(PageBreak())

    rl_doc.build(story, onFirstPage=_chrome, onLaterPages=_chrome)
    return buf.getvalue()


# ---------------------------------------------------------------------------
# S3 upload helper
# ---------------------------------------------------------------------------

def upload_to_s3(data: bytes, s3_key: str, content_type: str) -> str:
    """
    Upload `data` to S3 at `s3_key`.
    Returns the S3 URL string, or empty string on failure.
    """
    try:
        import boto3
        bucket = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
        region = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
        if not bucket:
            logger.warning('[Export] AWS_STORAGE_BUCKET_NAME not set – skipping S3 upload')
            return ''
        s3 = boto3.client('s3', region_name=region)
        s3.put_object(
            Bucket=bucket,
            Key=s3_key,
            Body=data,
            ContentType=content_type,
        )
        return f'https://{bucket}.s3.{region}.amazonaws.com/{s3_key}'
    except Exception as exc:
        logger.error('[Export] S3 upload failed: %s', exc)
        return ''
