# Generated by Django 5.0 on 2025-12-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_systemmetrics_systemhealthcheck_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
