# Generated by Django 5.0 on 2026-04-01 07:43

import apps.pfd_quality.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PFDQDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('file_name', models.CharField(max_length=512)),
                ('s3_path', models.CharField(blank=True, max_length=1024)),
                ('original_file', models.FileField(blank=True, max_length=500, null=True, upload_to=apps.pfd_quality.models._pfdq_upload_path)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('excel_s3_url', models.CharField(blank=True, max_length=1024)),
                ('pdf_s3_url', models.CharField(blank=True, max_length=1024)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfdq_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pfdq_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PFDQDrawing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drawing_id', models.CharField(db_index=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=512)),
                ('page_index', models.PositiveSmallIntegerField(default=0)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawings', to='pfd_quality.pfdqdocument')),
            ],
            options={
                'db_table': 'pfdq_drawings',
                'ordering': ['page_index'],
            },
        ),
        migrations.CreateModel(
            name='PFDQFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sl_no', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('stream', 'Stream'), ('control', 'Control'), ('title_block', 'Title Block'), ('safety', 'Safety'), ('utility', 'Utility'), ('notes', 'Notes & HOLDs')], max_length=30)),
                ('rule_id', models.CharField(blank=True, max_length=50)),
                ('issue_observed', models.TextField()),
                ('action_required', models.TextField()),
                ('evidence', models.TextField(blank=True)),
                ('direction', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor'), ('info', 'Info')], default='major', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='pfd_quality.pfdqdrawing')),
            ],
            options={
                'db_table': 'pfdq_findings',
                'ordering': ['sl_no'],
            },
        ),
        migrations.CreateModel(
            name='PFDQProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pfdq_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pfdq_projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='pfdqdocument',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='pfd_quality.pfdqproject'),
        ),
    ]
